module.exports = {
  source: ['sd-input/src/sd-input.json'],
  fileHeader: {
    autoGeneratedFileHeader: () => {
      return [`Do not edit directly, this file was auto-generated`];
    },
  },
  platforms: {
    css: {
      transforms: ["attribute/cti", "name/cti/kebab", 
      "color/css","size/px","type/fontFamilies"],
      buildPath: 'tokens/',
      prefix: 'figma',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            fileHeader: 'autoGeneratedFileHeader',
          },
        },
      ],
    },
  },
  'type/fontFamilies':{
    type:'value',
    matcher: (token) => token.type === 'fontFamily',
    transformer: (token) => `'${token.value}'`,
  }
};

